import type { Metadata } from "next";

import "@repo/ui/globals.css";
import { Toaster } from "@repo/ui/components/sonner";
import { Geist, Geist_Mono } from "next/font/google";

import { Providers } from "./providers";

const fontSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontMono.variable}`}>
        <Toaster />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
