FROM python:3.11

WORKDIR /api

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/dev.txt requirements/base.txt ./requirements/

RUN python3 -m pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements/dev.txt

COPY . .

EXPOSE 5050

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
